### ISSUE TITLE
Daedalus displays only 20 wallets

### ISSUE THREAD

**Issue by geitir** [input-output-hk/daedalus#1167]
The most recent version of Daedalus for windows only graphically displays a maximum of 20 wallets even though more exist, with no way to click though to display more.

**Comment by nikolaglumac** [comment]
@geitir limit was introduced with the Daedalus 0.10.1 release: https://github.com/input-output-hk/daedalus/releases/tag/0.10.1 due to performance issues:

> **Limit of 10 wallets in Daedalus**
> Daedalus had a limit of showing only 10 wallets. Users who created more than 10 wallets were unable to use all of them. This has been changed and Daedalus now supports up to 20 wallets. Also, a check has been introduced which prevents the creation of more than 20 wallets.

In case you have created more than 20 wallets prior to this Daedalus version you will need to delete some of the shown wallets in order to see the missing one...

**Comment by geitir** [comment]
Yes, but with the introduction of pagination in api v1 this should no longer be an issue. And, really? Your solution is to delete prior wallets in order to see the newer ones?

**Comment by nikolaglumac** [comment]
@geitir this is not just a question of pagination.
In order to see the 20+ wallets in Daedalus the only thing you can do is to delete some of the visible ones. Of course, you could use direct API calls to fetch them too.
