### ISSUE TITLE
Can't connect to node's api

### ISSUE THREAD

**Issue by razchen** [input-output-hk/daedalus#1240]
After updating to 0.12 I can no longer connect using curl to cardano api.
I'm trying curl -k https://127.0.0.1:8090/api/v1/accounts
but i'm getting a "connection refused".

Can anyone help?

**Comment by nikolaglumac** [comment]
@razchen Daedalus 0.12.0 release introduces dynamic Cardano API port selection. This means that the API server will be available on a different port each time you run Daedalus.
In order to find the active port, you should look into the `Daedalus.log` and find a line like this:
```
[10:55:56.664] [info] [main] CardanoNode: received message: {"ReplyPort":51059}
```
...where the port is `51059`.

Then you can access the API by:
```
curl -k https://127.0.0.1:51059/api/v1/accounts
```
