### ISSUE TITLE
New Block Consolidation Status window suggested minor improvement

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/daedalus#1351]
Hi,
    The new Block Consolidation Status  window is pretty cool, but I have some suggestions to improve it.

1. If I open the Network Status window first, then open the Block Consolidation Status window, the Block Consolidation window appears underneath the Network Status window and is not visible. (at least on Mac OSX).
2. To leave the block storage window, it has a back arrow on the top left vice an X on the top right. I suggest the the windows should have a consistent look on feel on the exit method, although this is a very simple and minor thing.
<img width="1013" alt="Screen Shot 2019-03-20 at 7 23 23 AM" src="https://user-images.githubusercontent.com/25856278/54682393-2c237c00-4ae5-11e9-83e9-b0bcff9cb72f.png">
<img width="1011" alt="Screen Shot 2019-03-20 at 7 23 53 AM" src="https://user-images.githubusercontent.com/25856278/54682395-304f9980-4ae5-11e9-914d-0f900178862c.png">
<img width="1009" alt="Screen Shot 2019-03-20 at 7 24 49 AM" src="https://user-images.githubusercontent.com/25856278/54682398-32b1f380-4ae5-11e9-80f6-15aa703887d6.png">

**Comment by nikolaglumac** [comment]
Hi @rickymac68,

Thanks for the suggestions.
However, these two screens are quite different:
- Network status is a dialog/overlay (which is why it opens on top of everything else and the reason why it has a "X" closing button on the top right),
- Block consolidation screen is a, well, screen.

We will not be modifying this behavior.

Cheers!

**Comment by rickymac68** [comment]
Hi Nikola,
    Well in that case, the About Daedalus dialog/overlay is missing the "X" closing button. What I am getting at here is we have 3 screens selectable from the same menu shown below, and all 3 have a different way of closing them for About Daedalus, Block Consolidation Status, and Network Status menu selections. It seems pretty simple for now, but I imagine as Daedalus grows there will be more inconsistencies between how the screens and overlays work. I don't think the average user will have a hard time with it, and the average user is not going to care about the difference between the definition of an overlay or a screen, they are just going to expect consistency. No biggie to me.

Cheers,
Rick

<img width="1004" alt="About-Daedalus" src="https://user-images.githubusercontent.com/25856278/54730353-d25f9800-4b5e-11e9-9300-b7ecd915bba4.png">

**Comment by nikolaglumac** [comment]
Hi @rickymac68,

Thanks for further suggestions.
The "About dialog" is once again something else - but yes - it should at least have the same close button as the paper wallet certificate. We will make it so for the next release.

Thanks!

**Comment by nikolaglumac** [comment]
One further note @rickymac68 - we actually have 4 screens that you can open from the application menu:
1. About dialog/overlay
2. Ada redemption screen
3. Network status dialog/overlay
4. Block consolidation screen

For me the only inconsistency is that the About dialog is missing a closing "x" button.

**Comment by rickymac68** [comment]
Nikola,
    Good point, you identified another inconsistency that I overlooked. The Ada Redemption screen is missing the back arrow. I am glad you are open to feedback. I will open a separate issue for this problem. Maybe eventually there will be some consistency with how the windows inside Daedalus work so the look and feel is standardized between each overlay or screen or whatever else pops up.

**Comment by nikolaglumac** [comment]
You don't have to do that @rickymac68 as Ada redemption screen will be removed in the next Daedalus release.

**Comment by nikolaglumac** [comment]
Also, there is nothing wrong with the "Ada redemption" screen as that screen has a normal wallet sidebar navigation in place - which "Block consolidation" screen can not have as it is reachable even if your wallet is not synced...

**Comment by nikolaglumac** [comment]
Hi @rickymac68 - here's the issue for the change you have requested to be done on the "About" dialog: https://github.com/input-output-hk/daedalus/issues/1357

**Comment by nikolaglumac** [comment]
@rickymac68 we will leave this issue open. The plan is to redesign the Network status screen and then we will have same UX pattern for the closing of both Network status and Block consolidation screens.

**Comment by nikolaglumac** [comment]
There was a question @rickymac68 posted as a part of his video (https://www.youtube.com/watch?v=e9jiCB8bAXU) about the navigation to the Daedalus *Block Consolidation Screen* which is available from the application menu: `Daedalus > Block Consolidation Screen`.

![1](https://user-images.githubusercontent.com/376611/54769134-ebb92080-4c00-11e9-98ce-0dbb56825c29.png)

@rickymac68 suggested that instead of through the application menu this screen should be reachable by clicking on the "Block syncing status" icon available in the main UI. 
This is a valid suggestion, however, this screen is mostly used by users facing syncing issues due to a problem with the block consolidation process. This means that these users are actually unable to reach the main UI and thus they can't see this icon which was the main reason behind putting the link to this screen to the application menu which is available regardless of the syncing progress.

![2](https://user-images.githubusercontent.com/376611/54769245-199e6500-4c01-11e9-841d-cbc7422e034e.png)

**Comment by nikolaglumac** [comment]
This issue has been resolved in Daedalus `0.14.0`: https://github.com/input-output-hk/daedalus/releases/tag/0.14.0 (release notes: https://iohk.zendesk.com/hc/en-us/articles/360033778753).

> **Unified look and feel of modal windows**
> Modal windows in Daedalus now have a unified look and feel. This affects the ‘About’ window, ‘Block consolidation status’ window and ‘Daedalus diagnostics’ window.
