### ISSUE TITLE
Ada Redemption screen is missing the back arrow 

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/daedalus#1356]
Hi,
   The Ada Redemption screen is missing the back arrow to exit the screen, adding to the inconsistencies in how different screens and overlays in Daedalus are exited or navigated. Here are some example screen captures to show the missing arrow.

<img width="1146" alt="AdaRedemption" src="https://user-images.githubusercontent.com/25856278/54745201-576aa180-4b9f-11e9-9690-cfc9c8e1d079.png">

<img width="1147" alt="BlockConsolidation" src="https://user-images.githubusercontent.com/25856278/54745214-5afe2880-4b9f-11e9-8ae2-4d672fd42ead.png">

**Comment by nikolaglumac** [comment]
Hi @rickymac68,

As pointed out earlier - the "Ada redemption" screen has a normal wallet sidebar navigation and thus it makes no sense to show the back arrow in this screen.
The block consolidation screen needs to be available even before Daedalus syncs and thus we can not show the same navigation there.

PS. We will be removing Ada redemption screen in the next Daedalus release.

Cheers!

**Comment by nikolaglumac** [comment]
Here's the plan @rickymac68:
- Ada redemption screen will not be changed (it will be removed).
- About dialog will get a standard "x" closing button in order to make it consistent with the other dialogs.
- Network status overlay will remain as is (this is an overlay and not a dialog!).
- Block consolidation screen will remain as is.
