### ISSUE TITLE
classnames lib - Object Syntax

### ISSUE THREAD

**Issue by lrosa007** [input-output-hk/daedalus#1434]
This isn't a bug or a problem that requires fixing.

I noticed that this project uses `classnames`, which is great, but in many places the project is using ternary operators for toggling classes when the object style eliminates this need completely.

Example:

* [current](https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/components/staking/stake-pools/StakePoolTooltip.js#L121)
```js
const componentClassnames = classnames([
  styles.component,
  isVisible ? styles.isVisible : null,
  flipHorizontal ? styles.flipHorizontal : null,
  flipVertical ? styles.flipVertical : null,
]);
```

* could instead be
```js
const componentClassnames = classnames(styles.component, {
    [styles.isVisible]: isVisible,
    [styles.flipHorizontal]: flipHorizontal,
    [styles.flipVertical]: flipVertical,
});
```

when `classnames` receives an object it concatenates the keys for any values that are true.

I think the latter reads much cleaner.

This isn't critical but I figured it was worth mentioning. If there was a specific reason this style was avoided, then I apologize in advance. If this is something everyone likes, I will be happy to put together a PR for these changes.

Love all the work 🙂

**Comment by daniloprates** [comment]
@lrosa007 that is a great suggestion. I have added a card on our development board for that to be implemented. Thank you.

**Comment by lrosa007** [comment]
@daniloprates does that I mean I should just leave it to you all?

**Comment by daniloprates** [comment]
Hi @lrosa007,

You are very welcome to implement it if you wish. We still don't have a Contributing Guide, so I will add some steps that need to be followed, in order to fit in our workflow.

* Create a branch called `feature/ddw-717-change-classnames-from-array-to-object`
* For each commit, please do in the format `[DDW-717] {description}`
* Once you pushed the first commit, create a pull request, adding the following description: "This PR replaces the use of arrays by objects when using `classnames`". No need for "## Todo" or "## Screenshots". Add the labels "WIP", "feature", "release-0.14.0" and "contribution".
* Add an entry to the CHANGELOG file under `## vNext` > `### Features`, with the following: 
```
* Replaced the use of arrays by objects when using `classnames` [PR{123}]({pr-link})"
```
* Remove the "WIP" label once it's all done.
* Add me as a reviewer of the PR.

Please, let me know if you need any assistance and thanks for your support.

Danilo

**Comment by nikolaglumac** [comment]
@lrosa007 please let us know if you plan to work on this task. Thank you!

**Comment by lrosa007** [comment]
Yes sorry for the delayed response. I’ll get it done ASAP this weekend

**Comment by nikolaglumac** [comment]
Thanks @lrosa007! Looking forward to your contribution :)
We're here for you if you need any guidance!

**Comment by lrosa007** [comment]
@nikolaglumac 
@daniloprates 

Ok changes are in #1465 

Github seems to be not letting me add the labels that were requested.

**Comment by daniloprates** [comment]
> Ok changes are in #1465

@lrosa007 that's an awesome contribution. Is the PR ready to be reviewed?

Thanks,
Danilo

**Comment by lrosa007** [comment]
@daniloprates yes I think so
