### ISSUE TITLE
Daedalus installer v 0.13.1 security certificate expired for Windows 64 bit

### ISSUE THREAD

**Issue by crisogenus** [input-output-hk/daedalus#1451]
The Daedalus installer version 0.13.1 for Windows 64 bit has an expired security certificate.

I downloaded it from https://daedaluswallet.io/#download and realized the security certificate was expired so I did not install Daedalus (although the Sha256 checksum seems to be fine). I'd rather wait for the security certificate to be renewed.

Can somebody PLEASE renew it and update the website with a fresh up to date Daedalus installer for Windows 64 bit? Thank you.

**Comment by disassembler** [comment]
The build was created prior to the expiration date of the signing certificate. Newer releases will be signed by the new certificate. There's complications with rebuilding the same build with a different signing certificate because of how update proposals work with Cardano. It's common practice to not rebuild old code with a new signing certificate after it expires and wait for a new release.

**Comment by crisogenus** [comment]
Thank you.
That is an answer that makes sense and now I can finally install Daedalus, despite the expired certificate.

-----------------

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
