### ISSUE TITLE
Update overwrites personalized configs

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/daedalus#1539]
For example if nodeDbPath value in launcher-config.yaml was changed to another path, the update replaced the entire file with default values.

not sure what would be a good way to allow and store personalized settings and "re-inject" them after an upgrade.

**Comment by nikolaglumac** [comment]
Hello @gufmar,

Modifying launcher-config.yaml is not something you should do. This is not considered to be a "normal" usage and thus it is not something the update mechanism expects.
I believe you will have to update the path again manually in order to restore your custom `nodeDbPath`.

@cleverca22 do you have any suggestions here?

Thanks!

**Comment by nikolaglumac** [comment]
Modifying `launcher-config.yaml` is not something you should be doing.
If you are interested in changing the paths of where chain data is stored, I suggest you to follow these steps: https://github.com/input-output-hk/daedalus/issues/605#issuecomment-771782614
