### ISSUE TITLE
Delegation Stuck - cannot undelagate

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/daedalus#2087]
I delegated to a pool with around 10 ADA, it seemed to go through no problem.
Now the delegation centre page says 'undelegated' but when I click on stake pools it shows it is delegated.
I cannot seem to undelegate now. it's stuck like that.

**Comment by willcbanks** [comment]
[](url)

**Comment by nikolaglumac** [comment]
@willcbanks can this issue be closed?

**Comment by nikolaglumac** [comment]
The "undelegation" is not present in recent Daedalus builds but it will be made available soon.

**Comment by ovidb** [comment]
@nikolaglumac what build have it? I have quite a lot of funds blocked because I wasn't aware you can not undelegate once you delegated is there any other way?

**Comment by nikolaglumac** [comment]
@ovidb delegation does not block any funds except for the 2 ADA deposit. No builds contain the undelegation feature yet but you don't need it to move your funds.

**Comment by ovidb** [comment]
Ok sorry, I'm just stupid, I looked at the wrong wallet. What basically happened is I transferred from an old Byron wallet into a new Shelly to be able to stake it, which I did. I was now looking at the old wallet and thought that there was actually a transaction toward the pool because of the name I've chosen for the wallet. 

Thanks for opening my eyes.

**Comment by nikolaglumac** [comment]
Glad to help! Have a nice day!
