### ISSUE TITLE
Stake pool list has some suspicious sorting patterns

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/daedalus#2093]
I will attach a screenshot to the issue. If this is a problem with cardano-wallet, please let me know and I will raise a github issue in their repo.

Daedalus 1.6.0 STN5 #13825 on Mac OS, pointing at MC4 network.

Pools from about position 98 till last one (229) seem to be primarily sorted by their unique pool id value, which seems less than ideal (even random order would be more preferred to this, imho). So pools in 98-100 range have pool ids like 00a-00f, while the last pools in 220-229 range have pool ids starting with f.

As a small aside, pool id value does not appear to be in the list of fields that can be searched on to uniquely identify a pool.

**Comment by bergr01** [comment]
![Screen Shot 2020-07-27 at 2 31 43 pm](https://user-images.githubusercontent.com/4503791/88503931-6d4f6880-d016-11ea-87eb-6f69435e7ef9.png)

**Comment by glitch40** [comment]
Also the color gradient makes them appear they are offline or under performing pools without having performance metrics listed there is no real way to tell how these pools perform or are ranked to any wallet user.

**Comment by Crypto2099** [comment]
I would argue that the problem extends much further up the list than position 98... can someone please explain to me how "LAMBO" pool still qualifies for 10th place by any metric discussed/mentioned in any previous IOHK/CF documentation?

![image](https://user-images.githubusercontent.com/63186174/88504390-7ba37300-cf89-11ea-8880-95b3f31bc0e6.png)

**Comment by Crypto2099** [comment]
Seems like the math has been done and just wantonly disregarded?

![image](https://user-images.githubusercontent.com/63186174/88504613-1dc35b00-cf8a-11ea-9917-00a6f146f04e.png)

**Comment by MarcelKlammer** [comment]
TITAN made a block a in epoch 6. We are still in epoch 6. Block is shown in Daedalus, but TITAN is ranked 216 as of now. After all of the other pools, that are ranked by their poolID, that have 0 blocks created?

**Comment by sp33dy** [comment]
This is effecting Crazy Pool. I started at 164! Then jumped to 88 and then back to 256. I've just minted my first three blocks in epoch 7, have pledged 200k ADA and another 50k delegated (showing up), yet I've now slipped to 258!!! I'm behind people with 500 ADA pledge and 0 mints. If we were main net, I'd be quite distraught right now; especially with k=150 coming. Can this be given some urgency??

**Comment by Cylonyx** [comment]
This may help with any troubleshooting since I experienced the same thing [CYLNX]
Changes I made/noticed going from rank 180 to 28 with 50k Pledge and blocks produced:
- I initially registered my pool with less than the pledged amount in my pool wallet, then re-registered my pool. Still no rank change after creating more blocks or receiving rewards at end of Epoch.
- After getting off work, I saw I was rank 28 with a small amount of rewards. Prior to that, I did not have any staking rewards

**Comment by KtorZ** [comment]
Hi there! 
Few things to note: 

a) Pools are ordered by non-myopic member rewards which is a metric built to be "fair" and ... well, non-myopic (i.e. long-term and non-biased towards short-term view of the system). There are several things that enter into the calculation of the non-myopic member rewards, in particular: cost per epoch & margin, pool's pledge as well as the pool's _relative_ performance. 

b) To be clear about the _relative_ part: a pool that has produced only one block in the previous epoch may have a better rank than a pool that produced hundred blocks. A typical scenario could be that, given their respective stake, the former pool did produce all blocks it was _expected_ to whereas the latter pool may have missed (let's say, for the sake of example) half of its slots. Yet, the first pool was only elected for one block so it couldn't have a chance to produce more! That's partly why the metric is called "non-myopic", it looks at pools as if they were _just_ saturated (best case scenario for a pool) to see what could be the best ROI for users. In principle, if all players are rationale and delegate to the top k pools, then all players are maximizing their rewards and the system operate at full capacity. 

c) There are several "edge-cases" in the ordering of pools. In particular, pools that have an exactly equal non-myopic member rewards. At the moment, if pools that have identical non-myopic reward are sorted alphabetically. There's a fix coming up in cardano-wallet (see input-output-hk/cardano-wallet#1959) so that in case of a tie, pools are sorted arbitrarily (though consistently on a same machine). This way, across many wallet clients, pools are equally favored (on one wallet, pool A may show before pool B, but the order may be different on another wallet). 

d) Another "edge-case" (which is more or less linked to c)) is the case of freshly registered pools. Indeed, pool's ranking implies looking at performance... but pools are only entitled to leadership on the next epoch following their registration. Worse case, there are 2 epochs for which a pool is there and can't produce any blocks. At the moment, these pools are assigned the lowest non-myopic reward possible, which isn't fair (because then they don't a get a chance to get delegators). input-output-hk/cardano-wallet#1959 also brings an additional fix where freshly registered pools will get assigned a "default" rank based on the average of the top ranking pools so that they get a chance at launch, then, after 2 epochs, they'll get to their proper "deserved" position in the competition. There's also an upcoming fix from cardano-ledger coming soon that will make it possible to make the performance calculation a bit more "real-time" by looking at the performance on-the-fly instead of only at the end of epochs.

**Comment by bergr01** [comment]
Thanks for the detailed write-up. Hopefully these upcoming fixes arrive before mainnet and have adequate testing done on them 🤞 🤞 🤞

**Comment by Crypto2099** [comment]
I don't mean to be a squeaky wheel here, but when and where do operator pledge and a pool's saturation level come into play in the "non-myopic" rewards calculation? Instead we see a pool with 0 margin and minimum (340 ADA/epoch) fixed costs out-ranking pools that have substantially more pledge which, from a non-myopic perspective should be the opposite given that the pool with a higher pledge amount has more likelihood of producing blocks in excess of the fixed costs of operation even if they have a slightly higher margin percentage.

**Comment by tanwaarpornthip** [comment]
@KtorZ's write-up is a fantastic description of what IOHK wants the ranking to do. However, it still doesn't address the original question posted. If the math is done correctly, it should have zero correlation to the unique pool IDs. The fact that the OP can find pool ranking pattern just by using pool IDs means that the "non-myopic" reward calculation is pretty much ignored.

This is pretty much a bug in Daedalus and it will hurt all honest pool operators.

**Comment by bergr01** [comment]
> @KtorZ's write-up is a fantastic description of what IOHK wants the ranking to do. However, it still doesn't address the original question posted. If the math is done correctly, it should have zero correlation to the unique pool IDs. The fact that the OP can find pool ranking pattern just by using pool IDs means that the "non-myopic" reward calculation is pretty much ignored.
> 
> This is pretty much a bug in Daedalus and it will hurt all honest pool operators.

He answered it in his point #3 - 'At the moment, if pools that have identical non-myopic reward are sorted alphabetically.'

**Comment by sp33dy** [comment]
To follow-up on this. I will read above later today. The ranking kicked in, 2 epochs after my first mint. From that moment on, I moved with pace to 69 then 38; from 282!! Happier now, but it was quite disturbing for the first 4 epochs.

**Comment by nikolaglumac** [comment]
All sorting issues have been fixed long ago. Closing this ticket...
