### ISSUE TITLE
Delegation history in Daedalus 2.4.0 Delegation center is potentially confusing and needs labeled. 

### ISSUE THREAD

**Issue by Profsmith9000** [input-output-hk/daedalus#2230]
I suggest adding a label above Delegation history in the Delegation center to avoid delegator confusion. 

<img width="854" alt="delhistory" src="https://user-images.githubusercontent.com/42823258/98003013-78e7c380-1dab-11eb-880d-92ac2a0a9189.png">

Currently using for cardano testnet (DAEDALUS2.4.0 macOS build 14924, Cardano Node 1.21.1, Cardano Wallet 2020.10.13)

**Comment by TrevorBenson** [comment]
The way it is currently presented appears as if it is a delegation history, but changing delegation (at least within the same epoch the delegation was first declared) does not list more than one pool, which may be by design. For instance if delegattion to LICH changes to ABC then changes to XYZ it transitions through the below 4 states:
```
UNDELEGATED
UNDELEGATED -> [LICH]
UNDELEGATED -> [ABC]
UNDELEGATED -> [XYZ]
```

This was testing within a single epoch, so it may be possible that after an entire epoch it does become a "history" of delegation? If so then maybe it is only confusing during the first epoch of delegation. However this also seems like it would not be a good UX experience once the delegation history grows beyond 10-20 pool delegations. I won't be able to tell if this is the case however until after a couple of epochs of testing

If this is not intended to be a full history of wallet delegation I susggest instead of showing `UNDELEGATED -> [TICKER]` to transitioned from UNDELEGATED to DELEGATED like: 
```
UNDELEGATED
DELEGATED -> [TICKER]
```

**Comment by TrevorBenson** [comment]
The updates in the Daedalus Testnet 3.2.0-FC1 resolve my comments about confusion in delegation within the wallet. 

![Screenshot from 2021-01-23 11-41-46](https://user-images.githubusercontent.com/9167887/105612327-31e8e900-5d70-11eb-954c-59cd72e928d9.png)

@Profsmith9000 Does this cover your feature request so we could close the ticket out?

Thanks

**Comment by Profsmith9000** [comment]
@TrevorBenson Yep, that's much improved. I like the specified epochs above.  Will close.

**Comment by nikolaglumac** [comment]
Glad you like it @Profsmith9000 @TrevorBenson!
