### ISSUE TITLE
Add support for searching by pool id (bech32 and hex)

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/daedalus#2235]
Hard to believe but the support to search by pool id is still currently missing in latest version of Daedalus (2.4.1 - FC1#15023)... even though the pop-up with the pool details actually has a 'copy id' icon to copy pool ID into clipboard for copy/pasting needs.

Not being able to search by pool ID means a lot of the how-to-stake-with-our-pool guides are semi-useless when it comes to Daedalus experience, especially for cases where there is a spoof/fake pool with the same ticker symbol.

**Comment by hodlonaut** [comment]
A sound of crickets so far, @nikolaglumac ?

**Comment by nikolaglumac** [comment]
Hi @hodlonaut!
This task is in our current sprint which means it should be included in the next Daedalus release.
Thank you for your patience!
Cheers!

**Comment by nikolaglumac** [comment]
This has been released in https://github.com/input-output-hk/daedalus/releases/tag/3.1.0

**Comment by hodlonaut** [comment]
Not sure why this has been closed @nikolaglumac  - I have Flight 3.1.0 installed and the second part of the problem mentioned in the title (search by hex pool id value - e.g. 4deb0ba979fe7af5a5a4896ef68cdae029ad116542555cb422f46348 - that's the pool id syntax/format that is used on a number of community tools for example pooltool.io as well as referenced on people's websites - since that is the format that has been available from the launch of mainnet) doesn't seem to yield any results.

**Comment by nikolaglumac** [comment]
@hodlonaut Daedalus only displays stake pool ids in bech32 format and that is the one the search works with.
