### ISSUE TITLE
Pool meta with 254/255 character "description" not displayed in Daedalus

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/daedalus#2244]
The description length inside Daedalus appears to be lower than allowed by cardano-cli metadata verification as such it allows for a transaction that looks complete and correct. However the Daedalus wallet will not display the pool ticker / information tile until you reach the allowed limit inside of Daedalus. 

cardano-cli validates the metadata file as long as you are under the 255 limit however if the description contains the full 255 ( or 254) characters even though the metadata is allowed and validates the pool will not be displayed inside Daedalus unless the description is further reduced.  

cardano-cli shelley stake-pool metadata-hash --pool-metadata-file metatdata.json

If you go above the limit the command below will show:

Shelley command failed: stake-pool metadata-hash  Error: Error validating stake pool metadata: Error in $: "description" must have at most 255 characters, but it has 258 characters.

If you reduce the description to 254 pass verification and submit a re-registration on chain for the pool the pool will still not display until you further reduce the description and process another re-registration transaction.

**Comment by nikolaglumac** [comment]
@KtorZ @disassembler can you please comment on this?

**Comment by nikolaglumac** [comment]
@gnpf @ManusMcCole @mioriohk please check this on Monday 🙏

**Comment by KtorZ** [comment]
Note: when fetching from pool servers directly (and not from a smash instance), `cardano-wallet` is being quite defensive on what it fetches. In particular, it won't fetch more than `512` bytes of data from the remote server (which helps circumvent the gentlemen who uploaded a 3GB metadata file for instance...) 

512 bytes is already quite conservative as an upper-bound as we expect roughly:

- A name (at most 50 UTF-8 bytes)
- An optional description (at most 250 UTF-8 bytes)
- A ticker (at most 5 UTF-8 bytes)
- A homepage (at most 100 UTF-8 

Thus it could be problematic if: 

a) The metadata contains extra fields which eat up space.
b) Name, ticker or homepage are using "special" characters which need 2 or 4 UTF-8 bytes per character (like emojis for instance). 
c) The file is oddly formatted with a lot of spaces and newlines (because they'll count towards the limit fixed by the wallet). 

I am not sure about how SMASH handles that and whether it is applying more lenient or more strict constraints; but it may behave slightly differently when a SMASH server is configured.

**Comment by nikolaglumac** [comment]
Thanks @KtorZ <3
