### ISSUE TITLE
Spending password longer than 255 characters

### ISSUE THREAD

**Issue by valodiadeseynes** [input-output-hk/daedalus#2257]
I can't send any ADA from my wallet because my spending password (999 characters long) which I set for a Byron wallet in 2018 is now considered too long.

I get the error : 

"mainnet:Linux:4.19.0-12-amd64","ns":["daedalus","v2.5.0","*mainnet*"],"data":{"error":{"code":"bad_request","message":"Error in $.passphrase: passphrase is too long: expected at most 255 characters"}},"app":["daedalus"],"msg":"AdaApi::transferFunds error","pid":"","sev":"error","thread":""}

**Comment by nikolaglumac** [comment]
Hi @valodiadeseynes!
I am sorry to hear about your issues.
This is a [cardano-wallet](https://github.com/input-output-hk/cardano-wallet) Api error and we (Daedalus Team) can't do much about it since this password length rule is enforced on the Api level.
The only thing you can do now is to delete your wallet and restore it again from your 12-word recovery phrase while setting a shorter spending password. Please make sure you have your 12-word recovery phrase for this wallet prior to proceeding in this direction (you can check in the wallet settings screen).
Good luck!

**Comment by valodiadeseynes** [comment]
Agreed. Although, could I advise you to enforce a spending password limit of 255 characters upon wallet creation/restoration ?

At least for now. It'd prevent the sort of issue I've had.

**Comment by nikolaglumac** [comment]
We are already doing that...

![Screenshot 2020-11-30 at 18 18 43](https://user-images.githubusercontent.com/376611/100642036-8bb4d000-3338-11eb-83f7-c97ea3218da9.png)

**Comment by valodiadeseynes** [comment]
No you're not.

You put a max limit on the wallet name but you didn't do the same for the password fields. I just tested, I can still create wallets with passwords longer than 255 characters.

**Comment by nikolaglumac** [comment]
You are right! We will fix this in our next sprint! 
Thanks!

**Comment by nikolaglumac** [comment]
Hi @valodiadeseynes!
This bug has been fixed in: https://github.com/input-output-hk/daedalus/pull/2287 and will be released in next Daedalus release.
Thanks for the patience and for bringing this up!
Best,
N.

**Comment by nikolaglumac** [comment]
Hi @valodiadeseynes!
The fix for this issue has been released in Daedalus Mainnet 3.2.0.
Thanks for reporting this!
Cheers!
