### ISSUE TITLE
Sending Error

### ISSUE THREAD

**Issue by alex-stout** [input-output-hk/daedalus#2464]
Hi,

I'm having an issue sending ada. I have no pending transactions in the transaction list.

This is what the interface looks like after adding an address and amount.
<img width="1350" alt="Screen Shot 2021-03-17 at 5 04 52 PM" src="https://user-images.githubusercontent.com/17804548/111545271-c73aa500-8743-11eb-92a7-b6e78f2829e0.png">

And here is the console error that I am getting in when this happens:

<img width="907" alt="Screen Shot 2021-03-17 at 5 04 16 PM" src="https://user-images.githubusercontent.com/17804548/111545221-b4c06b80-8743-11eb-8391-7b11482a3e9d.png">

**Comment by alex-stout** [comment]
Also a note about this wallet, the amount in the wallet is almost exclusively rewards from staking. I have created another wallet and transferred all the ada from the old -> new.

**Comment by alex-stout** [comment]
Here's the UTXO message:
![Screen Shot 2021-03-17 at 8 47 03 PM](https://user-images.githubusercontent.com/17804548/111561151-feb84a00-8761-11eb-9a4b-6822d1ea12cf.png)

**Comment by nikolaglumac** [comment]
It is not possible to move rewards in case you have no UTXOs in that wallet as you can not cover fees in that case.
This error message you saw is misleading and has been fixed in this PR: https://github.com/input-output-hk/daedalus/pull/2450
It has already been released on Daedalus Flight 4.0.2-FC3 and we will soon release it on Daedalus Mainnet too.

**Comment by alex-stout** [comment]
Awesome! Thank you.
