### ISSUE TITLE
Ledger Nano S Bug

### ISSUE THREAD

**Issue by chirkunov** [input-output-hk/daedalus#2484]
When trying to send funds, the Ledger (v. 1.6.1 with up to date Cardano App) with 24 seed phrase + passphrase is stuck on the message "Waiting for commands..." and the Deadalus Mac OS X app (3.3.2#16919) on "Connect the "xxxxxxx" device and enter your PIN to unlock it."

On a second computer it worked fine for the first transaction, after playing with it for a bit and declining transactions it stopped working as well. Transaction on adalite work seamlessly with the same Ledger.

From time to time it works and requests to export the public key and allows the transaction. But 95% of the time it doesn't work.

**Comment by chirkunov** [comment]
I just sent you the logs.

**Comment by nikolaglumac** [comment]
Thanks! I have received them!
@tomislavhoracek will investigate this as he is our hardware wallet specialist once he is back from his vacation next week.
Thanks for the patience!

**Comment by mreed911** [comment]
If you're also using Ledger Live, or any other Ledger-connected app, quit that app before using Ledger in Daedalus.  They seem to "contend" for the device.

**Comment by chirkunov** [comment]
@mreed911 Other Ledger-connected apps are definitely not running. The second mac doesn't have any other Ledger apps installed at all and Chrome was not running in the background.

**Comment by nikolaglumac** [comment]
@tomislavhoracek will get back to you next week.
Thanks for the patience!

**Comment by tomislavhoracek** [comment]
@chirkunov  Hi.
I investigated the issue you have and I want to check a few things if you don't mind.

1. So, as I saw, you have restored 2 hardware wallets. Both HW are restored from the same device (first one with and the second one without passphrase) right?

2. As I can see the device is successfully connected and recognized by Daedalus ( that definitely eliminates @mreed911 comment ), the weird thing is that when you initiated the transaction Daedalus is trying to connect the device on a different USB port than the device is set. Result is "infinite connecting" and error in the devTools console "DEVICE_NOT_CONNECTED" right?

3. May I ask you if you can install fresh Daedalus and make sure that you DELETED Daedalus state directory before that because maybe just local storage is in mess because of some update ?

**Comment by nikolaglumac** [comment]
@chirkunov any news?

**Comment by nikolaglumac** [comment]
@chirkunov please update Daedalus to the latest version (4.0.5) and let us know if that resolves the issue.

**Comment by chirkunov** [comment]
It did. I could not reproduce the issue anymore.

**Comment by nikolaglumac** [comment]
Thanks! Glad to hear that!
Closing this issue...
