### ISSUE TITLE
Question: undelegate

### ISSUE THREAD

**Issue by blgegaj** [input-output-hk/daedalus#2647]
Why the undelegate feature was created on a previous version the final setting set it as disabled on commit 40f577955cfb14cf477650fb7fec0fc2ed6c5adf, how will we be able to undelegate?

**Comment by nikolaglumac** [comment]
It has been temporarily disabled due to a missing automatic rewards withdrawal feature on the cardano-wallet Api side. In the scope of undelegation process, the wallet's staking key gets de-registered. Thus, you would "lose" your rewards account and all rewards still associated with it. In order to avoid this, we need an automatic withdrawal of all rewards into the wallet's UTXO balance. As soon as this is implemented on the cardano-wallet side we will make necessary adjustments in Daedalus code and enable the feature.
Thanks for the patience!

**Comment by blgegaj** [comment]
Thank you for your detailed answer.

**Comment by nikolaglumac** [comment]
You're welcome :-)
