### ISSUE TITLE
exporting public key fails continually on new trezor firmware

### ISSUE THREAD

**Issue by mikew1** [input-output-hk/daedalus#2790]
A few days ago I updated Trezor firmware to newest version, and daedalus exporting public key is now failing continually, so I am unable to spend funds.

I have tried, to no avail:

- disconnect & reconnect, multiple attempts
- different usb ports, multiple attempts

Trezor suite works fine, so the system is seeing the trezor.

I wonder if this means my hardware wallet within daedalus is now inaccessible until the next Daedalus update? (which takes account of the newest trezor firmware?)

Perhaps my mistake here was being too quick to update Trezor firmware without checking if Daedalus was already in-step with it? (I saw there were a lot of Cardano updates in the newest version of that firmware).  It may have been ideal if trezor had warned, if so; I didn't see anything about this in their changelog.

thanks.

**Comment by tomislavhoracek** [comment]
@mikew1 Thanks for letting us know.
It is not your mistake for sure!

New Trezor firmware is not backward compatible with the older `trezor-connect` library and we got a fixed version after the new FW release. 
We have a PR with the latest `trezor-connect` release and it will be included in one of the next Daedalus releases.
https://github.com/input-output-hk/daedalus/pull/2726

The workaround for this issue is to downgrade Trezor firmware to version `2.4.2`. 
Here are instructions: https://wiki.trezor.io/Firmware_downgrade

Thanks one more time.

**Comment by mikew1** [comment]
@tomislavhoracek Thanks for this info!  I've just tried following the instructions to downgrade though, and unfortunately I'm getting "not a correct firmware file" for `trezor-2.4.2.bin` in both trezor's web interface and trezor suite.  I've just contacted trezor support, but don't know how long they'll take to reply, and wondered if you knew anything about this in the meantime. Thanks for your help.
