### ISSUE TITLE
Can't Verify PGP Signature with Linux

### ISSUE THREAD

**Issue by MattMav** [input-output-hk/daedalus#2797]
Hi all, 

I followed [these](https://daedaluswallet.io/en/download/#modal=download_pgp_instructions_linux) instructions on how to verify the signature but I haven't been successful. 

I got up to the point to import the IOHK key and per the instructions I'm using the following: 

gpg2 --keyserver hkp://Keys.Openpgp.org --search-keys signing.authority@iohk.io

It's giving me the following errors however:

gpg: error searching keyserver: Server indicated a failure
gpg: keyserver search failed: Server indicated a failure

I'm using an Ubuntu based distro. 

Please let me know how I can successfully import the key. 

Thank you.

**Comment by danielmain** [comment]
Hi @MattMav I made a video testing that commands on `Ubuntu 20.04.3 LTS` and I have no Issues.


https://user-images.githubusercontent.com/4303099/147652455-38ab962e-2501-44d4-8789-8d451e1cc28e.mp4


Your problem seems not to be related to Daedalus nor IOHK. Try to import any other key and check if it works, if yes open this Issue again and share more details about your system.
