### ISSUE TITLE
Daedalus mainnet (4.7.0#20341) - "loading staking pools" takes forever.

### ISSUE THREAD

**Issue by monkey-jsun** [input-output-hk/daedalus#2834]
It has been running for 3 hours now, which is longer than anytime before.

Is there something wrong here?

**Comment by monkey-jsun** [comment]
It kept it running for about 7 hours and it is still loading.  Something is definitely wrong.  Any help?

**Comment by danielmain** [comment]
Hi @monkey-jsun please don't forget that Daedalus is a full node wallet, that means if you haven't open Daedalus recently it will take time (depending on your PC specs and Internet speed) to reach 100% blockchain sync. Daedalus downloads a full copy of the Cardano blockchain and independently validates every transaction in its history.

In my case, I haven't open Daedalus on Windows 11 for a while and after opening the stake pool page I see this:
![image](https://user-images.githubusercontent.com/4303099/150638040-dda27fe1-cb95-4a95-a0a5-8bdccf054340.png)

 I have to wait until is finished.

Is that what you are seeing?

**Comment by danielmain** [comment]
After a while (1-2hours) I got this screen @monkey-jsun 

![image](https://user-images.githubusercontent.com/4303099/150643002-347fe32b-cbd5-488b-b77b-6d67c91c06e5.png)

I would ask you to wait longer. You should be able to see at least the percentage. If not, please open this Issue again and share more details about your hardware/operating system because I cannot reproduce your problem ☹️

**Comment by monkey-jsun** [comment]
Well, this time I kept it running for 12 hours.  Let us see what happens next.

Please note the blockchain has already caught up, which itself takes a long time if not running for a while.  Right now it is purely spinning on loading stake pools.

**Comment by monkey-jsun** [comment]
It eventually came up.  *sigh*
