### ISSUE TITLE
Behavior when trying to transfer money from a wallet containing tokens so that the balance is less than 1 ADA

### ISSUE THREAD

**Issue by sakakibaraakio** [input-output-hk/daedalus#2932]
If you send money from a wallet that does not contain tokens so that the balance is less than 1 ADA, the balance that would have remained will be added to the fee.
This means that the balance after the transfer will never fall below 1 ADA, and the transfer will be successful.

However, it seems that this function does not work well with wallets that contain tokens, and you can move to the confirmation screen without adding the commission fee.

When I try to send money  entering the password, the message "Not enough ada for fees. Try sending a smaller amount.

**Comment by gabriela-ponce** [comment]
@sakakibaraakio Are you trying to move all the ADA on your wallet and not the tokens? 
If that's the case, Daedalus won't allow this action, since it calculates how much ADA you'd need to move the tokens you still have in the wallet and it prevents any transaction that would result in a smaller balance. 
In other words, you cannot empty a wallet with tokens, since you'd need ADA to operate them. 

We're aware the messaging and fee calculation might not be clear about this, so there will be future improvements in that regard.
Let me know if you have further questions!

**Comment by marcin-mazurek** [comment]
Hi @sakakibaraakio, I spoke to the team and apparently we've already got an improvement for this: https://github.com/input-output-hk/daedalus/pull/2783 - it will be shipped with the upcoming release, so stay tuned! 📻 

I'm going to close this issue, if you have any further questions or feedback, please leave a comment here and we'll reopen the issue.
