### ISSUE TITLE
Installer fails on Fedora 39

### ISSUE THREAD

**Issue by djay7777** [input-output-hk/daedalus#3211]
After running the installer, nothing gets written into the home directory.

After running the installer (daedalus-5.4.0-67194-mainnet-8dc751094-x86_64-linux.bin)

```
cardano2@zen3:~$ ls -la ~/.local
ls: cannot access '/home2/cardano2/.local': No such file or directory

cardano2@zen3:~$ ls -la /tmp/nixuJgF8k/home2/cardano2/
total 20
drwxr-xr-x. 5 cardano2 cardano2 4096 Jul 12 00:56 .
drwxr-xr-x. 3 cardano2 cardano2 4096 Jul 12 00:55 ..
drwxr-xr-x. 3 cardano2 cardano2 4096 Jul 12 00:56 .daedalus
drwxr-xr-x. 4 cardano2 cardano2 4096 Jul 12 00:56 .local
drwxr-xr-x. 2 cardano2 cardano2 4096 Jul 12 00:56 .nix-defexpr
```

**Comment by michalrus** [comment]
Thanks! You can see in the log that the installer is creating this directory:

```
mkdir: created directory '/home2/cardano2/.local/share/Daedalus/mainnet'
```

What is `/home2/`? It feels a bit non-standard, are you sure it's correct?

Then I see you're trying to list directory `.local` in your current directory which is `~` according to your shell or `$HOME`, or your home directory.

The only reason for this that I see is your `$HOME` directory not being `/home2/cardano2`?

Can you show me the output of:

```
❯ echo $HOME
```

And of `pwd` (the current directory) right before you try to `ls .local`:

```
❯ pwd
```

And also let's check if it's in the location that the installer deems your home:

```
❯ ls /home2/cardano2/.local/share/Daedalus/mainnet
```

**Comment by michalrus** [comment]
Uh-oh, wait, I re-read your original issue, so you said that everything ends up in `/tmp/nixuJgF8k/home2/cardano2/`, hmmmm.

Let me look at the code of the installer ⏳

**Comment by michalrus** [comment]
Okay, I get it. It's because [of this line](https://github.com/input-output-hk/daedalus/blob/7e73d49cbf38586ec1f7b5585d2ea23bfc90d1eb/installers/nix/nix-installer.nix#L10):

```
    nixUserChrootFlags = "-c -m /home:/home -p HOME";
```

The installer is being run from a `chroot`, where only `/home` is mounted as `/home`. We don’t know about `/home2`. This is rather silly, we should've mounted `$HOME` instead, sorry.

There have never been any reports about this, I'm assuming because almost no users have their `$HOME` under somewhere else than `/home`. But it's a good test case, thanks for finding it. :)

### Solution 1 – wait for 5.5.0

We're currently getting rid of the `chroot`, as it's problematic on the newest Ubuntu. The next release will be a simple installer which unpacks a completely portable directory which you can move to– and run from anywhere.

### Solution 2 – try the new installer today

You can download the installer from PR #3207 – from the Artifacts tab in the Linux section: https://buildkite.com/input-output-hk/daedalus/builds/23160

### Solution 3 – rename `/home2` back to `/home`

Or maybe symlink? I don’t know your exact setup.

**Comment by michalrus** [comment]
Happy to hear this :) Thanks for helping us test!
