### ISSUE TITLE
Daedalus Preview stuck at 99.45%

### ISSUE THREAD

**Issue by jonathanfishbein1** [input-output-hk/daedalus#3238]
Using 6.0.2

https://forum.cardano.org/t/daedalus-stuck-at-replaying-ledger-at-99-45/131669/9

**Comment by michalrus** [comment]
Preview needs a [new 10.× `cardano-node`](https://github.com/IntersectMBO/cardano-node/releases/tag/10.1.2).

We're in the process of upgrading, but it will take a little more work than usual:

* #3229,
* #3237,
* … and a few others soon.

**Comment by Knowledge-Wisdom-Understanding** [comment]
Can confirm this bug is also happening in the main Daedalus 6.0.2 release as well on Windows 10.

**Comment by Knowledge-Wisdom-Understanding** [comment]
Could this be related to using a symbolic link for the Daedalus Mainnet from `C:\Users\MYUSERNAME\AppData\Roaming` to `D:\` ? @michalrus 

A while back, the local state was taking up too much disk space on the default C:\ drive in windows so I created a symbolic link to D:\ drive via cmd.exe like:

```bat
cd "%USERPROFILE%\AppData\Roaming"
mklink /D "Daedalus Mainnet" "D:\Daedalus Mainnet"
```

This has worked great for a while but ever since upgrading to 6.0.2, am now currently stuck at "Replaying ledger from on-disk blockchain 89.80%" infinitely, as shown in the following screenshot.

![Daedalus-Stuck-Loading](https://github.com/user-attachments/assets/ea44b6d2-663e-4cf9-a75d-a52dfd494021)

It's been stuck at 89.80% for over 3 days..
Please advise.

Thanks!

**Comment by blockscout-oss** [comment]
> Could this be related to using a symbolic link for the Daedalus Mainnet from `C:\Users\MYUSERNAME\AppData\Roaming` to `D:\` ? @michalrus
> 
> A while back, the local state was taking up too much disk space on the default C:\ drive in windows so I created a symbolic link to D:\ drive via cmd.exe like:
> 
> ```batchfile
> cd "%USERPROFILE%\AppData\Roaming"
> mklink /D "Daedalus Mainnet" "D:\Daedalus Mainnet"
> ```
> 
> This has worked great for a while but ever since upgrading to 6.0.2, am now currently stuck at "Replaying ledger from on-disk blockchain 89.80%" infinitely, as shown in the following screenshot.
> 
> ![Daedalus-Stuck-Loading](https://private-user-images.githubusercontent.com/36655901/389302858-ea44b6d2-663e-4cf9-a75d-a52dfd494021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0ODAzNzgsIm5iZiI6MTczMjQ4MDA3OCwicGF0aCI6Ii8zNjY1NTkwMS8zODkzMDI4NTgtZWE0NGI2ZDItNjYzZS00Y2Y5LWE3NWQtYTUyZGZkNDk0MDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDIwMjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OGIzNGNhMDNmZWMxNTVjZDIxMzg3ZjNiYjM0MmFkZGNhYTIyZDg2NmUyZGRhOThiNDE4OWIxMWY5ZDYzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tUoQcUWEvYB3Bb9DMZOehXfbEjYJYRt4bl4KCY7cekA)
> 
> It's been stuck at 89.80% for over 3 days.. Please advise.
> 
> Thanks!

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [IOHK Help Center](https://cardano-zendesk.web.app/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Knowledge-Wisdom-Understanding** [comment]
Looks like a scam ^ 
I highly doubt that `https://cardano-zendesk[.]web[.]app/` is legit. The domain looks fraudulent as heck lol. Didn't click..
Watch out peoples. Don't click the link. Report web.app domain if ya have time. ✌️ 
The official IOHK Support URL is https://iohk.zendesk.com/hc/en-us
