### ISSUE TITLE
opening deadalus takes to long

### ISSUE THREAD

**Issue by TomDP** [input-output-hk/daedalus#593]
Hello,
Is there really a need for daedalus to be this slow?
If i want to send my coins to a market, it takes half an hour for daedalus to start up. It would be more useful if i can send my ada and keep syncing after that.

thanks

**Comment by dpmm99** [comment]
For one thing, despite that I don't think there's much random access and I do think the blocks are all the same size, someone made the absolutely terrible decision to store every block as a separate file, which may not even match up with the drive's sector size. Because of this, your hard drive has to sit there and look up each file individually, causing a massive slowdown, to the point that it actually rendered my SSD-based system unusable until I rebooted. Also, it makes the files use way more space than necessary on the drive.

**Comment by SebastienGllmt** [comment]
@dpmm99 this is tracked in https://github.com/input-output-hk/cardano-sl/pull/2628

**Comment by nikolaglumac** [comment]
Fixed in https://github.com/input-output-hk/daedalus/tree/0.12.0 with the introduction of blockchain storage consolidation: https://iohk.zendesk.com/hc/en-us/articles/360016060314
