### ISSUE TITLE
Administrative privilege on OS X

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/daedalus#626]
Does this wallet have to require an administrative privilege when being installed on OS X? It sounds quite unnecessary.

**Comment by pozyx** [comment]
[Also on Windows](https://github.com/input-output-hk/daedalus/issues/644)

**Comment by erikd** [comment]
I've compiled cardano/daedalus from source on Linux and it runs fine as a normal user.

**Comment by danunahui** [comment]
It requires a password when being installed, distributed in .pkg and pin an app to the dock after installation. All this is very strange and not required for most other apps.
I do not know if the password is required after installation, because the installer fails for me every time, so I unpack the pkg > Payload and move Daedalus.app to the Applications folder.

**Comment by nikolaglumac** [comment]
Duplicate of: https://github.com/input-output-hk/daedalus/issues/587
