### ISSUE TITLE
Export CSV of all transactions

### ISSUE THREAD

**Issue by davelab6** [input-output-hk/daedalus#642]
For tax purposes I want to export all the transactions in my Daedalus wallet, but I can see now way to do this other than using the built-in Developer Tools to extract the HTML and parse out my data myself.

**Comment by gubatron** [comment]
is there anybody already working on this?
Seems like a good first exploratory patch if nobody is working on it. I think I could make it happen.

**Comment by gubatron** [comment]
One year later, still no export .csv.

Doing accounting manually sucks guys. This should be a CORE feature of the wallet.

**Comment by tiredpixel** [comment]
Any update on this? I've just been looking more closely at the Daedalus wallet, and neither production nor flight appear to have this functionality. This is really pretty important when it comes to things like portfolio management and preparing taxes… I'm actually really surprised it's not there already. :/

**Comment by gubatron** [comment]
Bump, it's been two years guys, Daedalus should have this simple yet core feature for accounting.
Or perhaps there's a script we can use to talk to cardano node to export the transactions in JSON and then convert to csv?

**Comment by gubatron** [comment]
CC @DeeJayElly @disassembler @daniloprates @darko-mijic @CharlesHoskinson

**Comment by rdlrt** [comment]
Well - imo the Daedalus team does not operate with community's (`external`) priorities - besides their focus seems more on UI than UX , there are a few basic UX issues open since 2-3 years (this being one of them). Regardless , that's probably my bitter view ...

@gubatron - The dirty (probably one-time effort to write a small script) workaround would be connecting to the `cardano-wallet` (either use netstat, or use Daedalus -> Ctrl-D to grab the port number) , and then query API as per [here](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listTransactions).

Alternately for the port number, you can also modify the startup command for launcher to specify a static port

**Comment by darko-mijic** [comment]
The implementation of this feature is in progress.

**Comment by gubatron** [comment]
YES!!!!
Please also consider including the export of a detailed log regarding Staking Rewards, ideal fields would be:
date, amount earned, from what pool

**Comment by kylebehse** [comment]
Thanks, @darko-mijic !! Can't wait!! :-)

**Comment by nikolaglumac** [comment]
This feature will be available in the next Daedalus release.
We are running final QA on it at the moment: https://github.com/input-output-hk/daedalus/pull/2207

**Comment by nikolaglumac** [comment]
This _long awaited_ feature has been merged and will be released in the next Daedalus update 🎉 
Thank you for your patience @davelab6 @gubatron @tiredpixel @rdlrt @kylebehse 🙏 

![export-tx-history-lq](https://user-images.githubusercontent.com/376611/99153374-6ffaca00-26a8-11eb-9b96-989b757db1df.gif)

**Comment by gubatron** [comment]
YESSSSSSSSSS!!!!!

**Comment by nikolaglumac** [comment]
Released in: https://github.com/input-output-hk/daedalus/tree/2.5.0

Closing this ticket now... 

Thanks all!
